let stockPlatos = [
    {id: 1, nombre: "tallarines", tipo: "pasta", precio: 500, salsa: "blanca" },
    {id: 2, nombre: "tallarines", tipo: "pasta", precio: 500, salsa: "roja"},
    {id: 3, nombre: "tallarines", tipo: "pasta", precio: 500, salsa: "mixta"},
    {id: 4, nombre: "ravioles", tipo: "pasta", precio: 600, salsa: "blanca"},
    {id: 5, nombre: "ravioles", tipo: "pasta", precio: 600, salsa: "roja"},
    {id: 6, nombre: "ravioles", tipo: "pasta", precio: 600, salsa: "mixta"},
    {id: 7, nombre: "canelones", tipo: "pasta", precio: 700, salsa: "blanca"},
    {id: 8, nombre: "canelones", tipo: "pasta", precio: 700, salsa: "roja"},
    {id: 9, nombre: "canelones", tipo: "pasta", precio: 700, salsa: "mixta"},
    {id: 10, nombre: "asado", tipo: "parrilla", precio: 1000, salsa: "ninguna"},
    {id: 11, nombre: "asado", tipo: "parrilla", precio: 1000, salsa: "chimichurri"},
    {id: 12, nombre: "asado", tipo: "parrilla", precio: 1000, salsa: "criolla"},
    {id: 13, nombre: "empanada de carne", tipo: "entrada", precio: 80, salsa: "ninguna"},
    {id: 14, nombre: "empanada de carne", tipo: "entrada", precio: 80, salsa: "criolla"},
    {id: 15, nombre: "empanada de carne", tipo: "entrada", precio: 80, salsa: "4 quesos"},
    {id: 16, nombre: "empanada de humita", tipo: "entrada", precio: 80, salsa: "ninguna"},
    {id: 17, nombre: "empanada de humita", tipo: "entrada", precio: 80, salsa: "roja"},
    {id: 18, nombre: "empanada de humita", tipo: "entrada", precio: 80, salsa: "criolla"},
    {id: 19, nombre: "pollo al horno", tipo: "plato", precio: 400, salsa: "ninguna"},
    {id: 20, nombre: "pollo al horno", tipo: "plato", precio: 400, salsa: "limón"},
    {id: 21, nombre: "pollo al horno", tipo: "plato", precio: 400, salsa: "champignones" },
    {id: 22, nombre: "ensalada mixta", tipo: "guarnicion", precio: 200, salsa: "caesar"},
    {id: 23, nombre: "ensalada mixta", tipo: "guarnicion", precio: 200, salsa: "queso"},
    {id: 24, nombre: "papas fritas", tipo: "guarnicion", precio: 350, salsa: "ninguna"},
]